# Generated by Django 4.2.1 on 2023-06-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0005_alter_administrador_cargo_alter_vinilo_cara_delante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='probar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cara_delante', models.FileField(null=True, upload_to='productos')),
            ],
        ),
        migrations.AlterField(
            model_name='vinilo',
            name='cara_delante',
            field=models.ImageField(null=True, upload_to='media/productos'),
        ),
    ]
