# Generated by Django 4.2.1 on 2023-06-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0006_probar_alter_vinilo_cara_delante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='probar',
        ),
        migrations.AlterField(
            model_name='vinilo',
            name='cara_delante',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
