# Generated by Django 4.2.1 on 2023-06-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0007_delete_probar_alter_vinilo_cara_delante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinilo',
            name='cantidad',
        ),
    ]
