# Generated by Django 4.2.1 on 2023-06-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0009_vinilo_lista_canciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinilo',
            name='lista_canciones',
        ),
    ]
