# Generated by Django 4.2.1 on 2023-06-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0010_remove_vinilo_lista_canciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
    ]
