# Generated by Django 4.2.1 on 2023-06-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0012_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='region',
            field=models.CharField(choices=[('RM', 'Santiago'), ('Bio-Bio', 'Bio-Bio'), ('Araucania', 'Araucania')], max_length=50),
        ),
    ]
