# Generated by Django 4.2.1 on 2023-06-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0013_alter_cliente_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Sin enviar', 'Sin enviar'), ('En transito', 'En transito'), ('Completado', 'Completado')], max_length=100),
        ),
    ]
