# Generated by Django 4.2.1 on 2023-06-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0017_alter_clipedido_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipedido',
            name='pedido',
            field=models.IntegerField(),
        ),
    ]
